const String baseSupabaseUrl = 'https://kopngdclkvcdfoomcgme.supabase.co';
const String baseUrl = 'https://kopngdclkvcdfoomcgme.supabase.co/rest/v1/';
const String apiKey = 'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImtvcG5nZGNsa3ZjZGZvb21jZ21lIiwicm9sZSI6ImFub24iLCJpYXQiOjE3Mzk3OTY0NDEsImV4cCI6MjA1NTM3MjQ0MX0.xc0vYq3A4frTe2PLndrRzrWynen8HhPqfIGz-XhqvLA';
const String baseWebClientId = '437702837817-oanjui0aip793b04mc3c56sldkc04gl5.apps.googleusercontent.com'; 
const String productUrl = '${baseUrl}products_table?select=*,favorite_product(*),purchase_table(*)' ;
const String ratesUrl = '${baseUrl}rates_table?select=*&for_product=eq.' ;
const String commentUrl = '${baseUrl}comments_table';
const String favoriteUrl = '${baseUrl}favorite_product' ;
const String payMopApiKey = 'ZXlKaGJHY2lPaUpJVXpVeE1pSXNJblI1Y0NJNklrcFhWQ0o5LmV5SmpiR0Z6Y3lJNklrMWxjbU5vWVc1MElpd2ljSEp2Wm1sc1pWOXdheUk2TVRBeU56QTFPU3dpYm1GdFpTSTZJbWx1YVhScFlXd2lmUS5ZWl9iT0VISlZaYnJMYm9SQjFTa0NHeFMxV2ZIZVRGeTFfRHVxLTFGMHBRR2hfenM1ZUotYmdnYnN5SnBuenpnQXExYnBzVzVWRUVuN2hFY0xRaFdFUQ==';
const String iframeId = '903365';
const String integrationCardId = '4999245';
const String integrationMobileWalletId = '4999263';
const String purchaseUrl = '${baseUrl}purchase_table' ;
